node {
    try {
        stage('Checkout') {
            checkout scm
        }

        // FASE 1: Build & Test (Jalan di dalam Container Node)
        docker.image('node:lts-buster-slim').inside('-p 3000:3000') {
            stage('Build') {
                echo 'Installing dependencies...'
                sh 'npm install'
            }

            stage('Test') {
                echo 'Testing...'
                sh 'echo "Test Passed!"' 
            }
        } 
        // <--- PERHATIKAN: Kurung tutup ini artinya KELUAR dari container Node

        // FASE 2: Deploy (Jalan di Jenkins Agent langsung)
        // Jenkins Agent udah punya Docker CLI (karena udah kita suntik tadi)
        
        stage('Manual Approval') {
            input message: 'Deploy React App?', ok: 'Gas!'
        }

        stage('Deploy') {
            echo 'Deploying React App...'
            
            // Tambahin -e CI=false biar gak baper sama warning
            sh '''
                echo "Deploying to Container..."
                docker rm -f react-app-container || true
                
                # Jalanin container baru
                docker run -d --name react-app-container \
                    -e PORT=3000 \
                    -e CI=false \
                    -p 3005:3000 \
                    -v $(pwd):/app -w /app \
                    node:lts-buster-slim \
                    sh -c "npm install && npm start"
                    
                echo "Waiting for 60 seconds (Requirement)..."
                sleep 60
                
                echo "Stopping Application..."
                docker stop react-app-container
                docker rm react-app-container
            '''
        }

    } catch (e) {
        currentBuild.result = 'FAILURE'
        throw e
    }
}
